Need to rebuild

diff --git a/.github/workflows/publish_chart.yml b/.github/workflows/publish_chart.yml
--- a/.github/workflows/publish_chart.yml
+++ b/.github/workflows/publish_chart.yml
@@ -23,4 +23,4 @@ jobs:
       with:
         who-to-greet: Michael
     - name: Get the output time
-      run: echo "The time was ${{ steps.hello.outputs.time }}"
+      run: echo "The time was ${{ steps.hello.outputs.time }} needs to fail" && exit 1
